name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: shahriar001/subscription-tracker-backend
      BACKEND_VERSION: 2.0
      FRONTEND_IMAGE: shahriar001/subscription-tracker-frontend
      FRONTEND_VERSION: 1.0.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.DOCKER_ENV_FILE }}" > .env

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build all images with Docker Compose
        run: docker compose build

      - name: Tag backend and frontend images
        run: |
          docker tag subs-tracker-backend $BACKEND_IMAGE:$BACKEND_VERSION
          docker tag subs-tracker-backend $BACKEND_IMAGE:latest
          docker tag subs-tracker-frontend $FRONTEND_IMAGE:$FRONTEND_VERSION
          docker tag subs-tracker-frontend $FRONTEND_IMAGE:latest

      - name: Push backend and frontend images
        run: |
          docker push $BACKEND_IMAGE:$BACKEND_VERSION
          docker push $BACKEND_IMAGE:latest
          docker push $FRONTEND_IMAGE:$FRONTEND_VERSION
          docker push $FRONTEND_IMAGE:latest

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_OCI }}

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST_OCI }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          SSH_USER: ${{ secrets.SSH_USER_OCI }}
          SSH_HOST: ${{ secrets.SSH_HOST_OCI }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ssh $SSH_USER@$SSH_HOST '
            cd subscription-tracker/ && \
            rm -f docker-compose.production.yml && \
            curl -O https://raw.githubusercontent.com/Shahriar-Mahmud-Toha/SubscriptionTracker/master/docker-compose.production.yml && \
            docker compose -f docker-compose.production.yml pull && \
            docker compose -f docker-compose.production.yml up -d
          '

  build-and-push-backend-standalone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend standalone image
        run: |
          cd Backend/SubscriptionTracker
          docker build -f DockerFile.standalone -t shahriar001/subscription-tracker-backend-standalone:latest .

      - name: Push backend standalone image
        run: |
          docker push shahriar001/subscription-tracker-backend-standalone:latest